# Generated by Django 5.1.4 on 2026-09-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('contato', models.CharField(blank=True, help_text='Nome e telefone/e-mail do contato principal', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Placa, número de série, patrimônio ou outro código único da máquina', max_length=100, unique=True)),
                ('descricao', models.CharField(help_text='Ex: Empilhadeira Toyota 2.5t', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente ao qual a máquina está atualmente alocada (se aplicável)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['identificador'],
            },
        ),
    ]
