# Generated by Django 5.1.4 on 2026-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_maquina_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='identificador',
            field=models.CharField(blank=True, help_text='Placa, número de série, patrimônio ou outro código único da máquina (opcional, quando ainda não houver essa informação)', max_length=100, null=True, unique=True),
        ),
    ]
