# Generated by Django 5.1.4 on 2026-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_maquina_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='identificador',
            field=models.CharField(default=None, help_text='Placa, número de série, patrimônio ou outro código único da máquina', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
