# Generated by Django 5.1.4 on 2026-09-22 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REMESSA', 'Relatório Fotográfico de Remessa'), ('DEVOLUCAO', 'Relatório Fotográfico de Devolução'), ('CHECKLIST_MAQUINA', 'Checklist de Máquina')], max_length=30)),
                ('titulo', models.CharField(blank=True, help_text='Gerado automaticamente: TIPO + IDENTIFICADOR DA MÁQUINA + DATA', max_length=255, unique=True)),
                ('responsavel', models.CharField(help_text='Quem preencheu o relatório', max_length=255)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pdf_gerado', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('cliente', models.ForeignKey(blank=True, help_text='Preenchido automaticamente a partir da máquina, se não informado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='core.cliente')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='core.maquina')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pergunta', models.CharField(max_length=255)),
                ('resultado', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não conforme'), ('NAO_APLICAVEL', 'Não aplicável')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklist.checklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('tirada_em', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklist.checklist')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklist.itemchecklist')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['tirada_em'],
            },
        ),
    ]
