# Generated by Django 5.1.4 on 2026-09-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('core', '0004_alter_maquina_identificador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['ordem', 'tirada_em'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='foto',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a posição da foto no PDF final'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente para o qual esta operação foi feita', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='core.cliente'),
        ),
    ]
