# Generated by Django 5.1.4 on 2026-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_foto_options_foto_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='medidor',
            field=models.CharField(blank=True, help_text='Leitura do horímetro/odômetro no momento do checklist', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist',
            name='referencia_sistema',
            field=models.CharField(blank=True, help_text='Código de referência no sistema/ERP, se houver', max_length=100),
        ),
    ]
